import { execFile } from "child_process";
import * as fs from "fs/promises";
import * as path from "path";
import { promisify } from "util";

const execFileP = promisify(execFile);

const ENV_PATH = process.env.UPSTREAM_ENV_PATH ?? "/app/upstream.env";
const UPSTREAM_PORT = Number(process.env.UPSTREAM_PORT ?? 8000);

export interface UpstreamEnv {
  url: string;
  username: string;
  appPassword: string;
  authToken: string;
}

export async function writeEnv(env: UpstreamEnv): Promise<void> {
  const lines = [
    "# Auto-generated by nextcloudmcp wrapper — do not edit by hand",
    `NEXTCLOUD_HOST=${env.url}`,
    `NEXTCLOUD_USERNAME=${env.username}`,
    `NEXTCLOUD_PASSWORD=${env.appPassword}`,
    `AUTH_TOKEN=${env.authToken}`,
  ];
  const dir = path.dirname(ENV_PATH);
  try {
    await fs.mkdir(dir, { recursive: true });
  } catch {
    /* ignore */
  }
  await fs.writeFile(ENV_PATH, lines.join("\n") + "\n", { mode: 0o600 });
}

export async function restart(): Promise<void> {
  try {
    await execFileP("supervisorctl", ["restart", "nextcloud-mcp-upstream"], {
      timeout: 10_000,
    });
  } catch (err) {
    // In local dev without supervisord, silently skip — the caller can restart manually.
    const msg = err instanceof Error ? err.message : String(err);
    if (!/ENOENT|not found/i.test(msg)) {
      console.warn("supervisorctl restart failed:", msg);
    }
  }
}

export async function health(): Promise<boolean> {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), 1500);
  try {
    const res = await fetch(`http://127.0.0.1:${UPSTREAM_PORT}/health/ready`, {
      method: "GET",
      signal: ctrl.signal,
    });
    return res.ok;
  } catch {
    return false;
  } finally {
    clearTimeout(timer);
  }
}

export function upstreamPort(): number {
  return UPSTREAM_PORT;
}
